name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run.'
        required: true
        default: 'prod-deploy'

jobs:
  test:
    name: validate and test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
